manifest:
  remotes:
    - name: oldmanz
      url-base: https://github.com/oldmanz
  projects:
    - name: zmk-urob
      remote: oldmanz
      revision: main
      import: app/west.yml
  self:
    path: config